#############################################################################
# Makefile for building: build/debug/Oscillo
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  Oscillo.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile Oscillo.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_OPENGLWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/qt6 -I/usr/include/qt6/QtCharts -I/usr/include/qt6/QtOpenGLWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSerialPort -I/usr/include/qt6/QtCore -Ibuild/debug/.moc -I/usr/lib/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Oscillo1.0.0
DISTDIR = /home/neo/Gits/Msc-Physics/Projects/C++/Oscillo/build/debug/.obj/Oscillo1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) /usr/lib/libQt6Charts.so /usr/lib/libQt6OpenGLWidgets.so /usr/lib/libQt6PrintSupport.so /usr/lib/libQt6Widgets.so /usr/lib/libQt6OpenGL.so /usr/lib/libQt6Gui.so /usr/lib/libGLX.so /usr/lib/libOpenGL.so /usr/lib/libQt6SerialPort.so /usr/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/debug/.obj/

####### Files

SOURCES       = src/main.cpp \
		src/qcustomplot.cpp build/debug/.moc/moc_qcustomplot.cpp
OBJECTS       = build/debug/.obj/main.o \
		build/debug/.obj/qcustomplot.o \
		build/debug/.obj/moc_qcustomplot.o
DIST          = /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/uic.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		Oscillo.pro src/Oscillo.hpp \
		src/qcustomplot.h src/main.cpp \
		src/qcustomplot.cpp
QMAKE_TARGET  = Oscillo
DESTDIR       = build/debug/
TARGET        = build/debug/Oscillo


first: all
####### Build rules

build/debug/Oscillo:  $(OBJECTS)  
	@test -d build/debug/ || mkdir -p build/debug/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Oscillo.pro /usr/lib/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/uic.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		Oscillo.pro \
		/usr/lib/libQt6Charts.prl \
		/usr/lib/libQt6OpenGLWidgets.prl \
		/usr/lib/libQt6PrintSupport.prl \
		/usr/lib/libQt6Widgets.prl \
		/usr/lib/libQt6OpenGL.prl \
		/usr/lib/libQt6Gui.prl \
		/usr/lib/libQt6SerialPort.prl \
		/usr/lib/libQt6Core.prl
	$(QMAKE) -o Makefile Oscillo.pro
/usr/lib/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/qt6/mkspecs/common/unix.conf:
/usr/lib/qt6/mkspecs/common/linux.conf:
/usr/lib/qt6/mkspecs/common/sanitize.conf:
/usr/lib/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt6/mkspecs/common/g++-base.conf:
/usr/lib/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/qt6/mkspecs/qconfig.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/qt6/mkspecs/features/qt_config.prf:
/usr/lib/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt6/mkspecs/features/toolchain.prf:
/usr/lib/qt6/mkspecs/features/default_pre.prf:
/usr/lib/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/qt6/mkspecs/features/default_post.prf:
/usr/lib/qt6/mkspecs/features/warn_on.prf:
/usr/lib/qt6/mkspecs/features/qt.prf:
/usr/lib/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/qt6/mkspecs/features/resources.prf:
/usr/lib/qt6/mkspecs/features/moc.prf:
/usr/lib/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/qt6/mkspecs/features/uic.prf:
/usr/lib/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/qt6/mkspecs/features/file_copies.prf:
/usr/lib/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/qt6/mkspecs/features/exceptions.prf:
/usr/lib/qt6/mkspecs/features/yacc.prf:
/usr/lib/qt6/mkspecs/features/lex.prf:
Oscillo.pro:
/usr/lib/libQt6Charts.prl:
/usr/lib/libQt6OpenGLWidgets.prl:
/usr/lib/libQt6PrintSupport.prl:
/usr/lib/libQt6Widgets.prl:
/usr/lib/libQt6OpenGL.prl:
/usr/lib/libQt6Gui.prl:
/usr/lib/libQt6SerialPort.prl:
/usr/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Oscillo.pro

qmake_all: FORCE


all: Makefile build/debug/Oscillo

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/Oscillo.hpp src/qcustomplot.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/Oscillo.cpp src/qcustomplot.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/debug/.moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/debug/.moc/moc_predefs.h
build/debug/.moc/moc_predefs.h: /usr/lib/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -fPIC -dM -E -o build/debug/.moc/moc_predefs.h /usr/lib/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/debug/.moc/moc_qcustomplot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/debug/.moc/moc_qcustomplot.cpp
build/debug/.moc/moc_qcustomplot.cpp: src/qcustomplot.h \
		build/debug/.moc/moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/neo/Gits/Msc-Physics/Projects/C++/Oscillo/build/debug/.moc/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/neo/Gits/Msc-Physics/Projects/C++/Oscillo -I/home/neo/Gits/Msc-Physics/Projects/C++/Oscillo -I/usr/include/qt6 -I/usr/include/qt6/QtCharts -I/usr/include/qt6/QtOpenGLWidgets -I/usr/include/qt6/QtPrintSupport -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSerialPort -I/usr/include/qt6/QtCore -I/usr/include/c++/12.2.1 -I/usr/include/c++/12.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/12.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/include-fixed -I/usr/include src/qcustomplot.h -o build/debug/.moc/moc_qcustomplot.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/debug/.obj/main.o: src/main.cpp src/Oscillo.cpp \
		src/Oscillo.hpp \
		src/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/main.o src/main.cpp

build/debug/.obj/qcustomplot.o: src/qcustomplot.cpp src/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/qcustomplot.o src/qcustomplot.cpp

build/debug/.obj/moc_qcustomplot.o: build/debug/.moc/moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_qcustomplot.o build/debug/.moc/moc_qcustomplot.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

